eduly-jobs/config/routes.rb
Rails.application.routes.draw do

	root 'sessions#new'

	resources :landings, only: [:index]
	resources :empl_designations do
		post 'import', on: :collection
	end

	resources :empl_organisations do
		post 'import', on: :collection
	end

	resources :empl_cities do
		post 'import', on: :collection
	end

	resources :empl_job_types do
		post 'import', on: :collection
	end

	resources :empl_jobs do
		post 'import', on: :collection
	end

	resources :empl_states do
		post 'import', on: :collection
	end
	# Signup routes
	resources :admin_users, only: [:create]
	get "signup", to: "admin_users#new", as: "signup"

	# login routes
	resources :sessions, only: [:create]
	get "login", to: "sessions#new", as: "login"
	delete "logout", to: "sessions#destroy", as: "logout"

end

eduly-jobs/app/models/empl_state.rb
class EmplState < ActiveRecord::Base
	before_save :lower_state_name

	def lower_state_name
		self.state_name = state_name.downcase.split.map(&:capitalize).join(" ")
	end

	def self.to_csv
		CSV.generate do |csv|
			csv << column_names

			all.each do |empl_state|
				csv << empl_state.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			empl_state = find_by_id(row["id"]) || new
			empl_state.attributes = row.to_hash
			empl_state.save!
		end
	end

	# Assoications
	has_many :empl_cities

	# Validations
	validates :state_name, presence: true
end

eduly-jobs/app/controllers/empl_states_controller.rb
class EmplStatesController < ApplicationController

	before_filter :authorize
	before_action :set_empl_state, only: [:show, :edit, :update, :destroy]

	def index
		@empl_states = EmplState.order("state_name")

		respond_to do |format|
			format.html
			format.csv { send_data @empl_states.to_csv }
		end
	end

	def show
	end

	def new
		@empl_state = EmplState.new
	end

	def create
		@empl_state = EmplState.new(empl_state_params)

		if @empl_state.save
			redirect_to @empl_state, notice: 'New Employment State has been created successfully.'
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @empl_state.update(empl_state_params)
			redirect_to @empl_state, notice: 'Employment State has been updated successfully.'
		else
			render 'edit'
		end
	end

	def destroy
		@empl_state.destroy
		redirect_to empl_states_path, notice: 'Employment State has been deleted successfully.'
	end

	def import
		EmplState.import(params[:file])
		redirect_to empl_states_path, notice: "Empl State imported."
	end


	private
		def empl_state_params
			params.require(:empl_state).permit(:state_name)
		end

		def set_empl_state
			@empl_state = EmplState.find(params[:id])
		end
end

eduly-jobs/app/helpers/empl_states_helper.rb
module EmplStatesHelper
end

eduly-jobs/app/views/empl_states/_form.html.erb
<%= form_for @empl_state do |f| %>
	<% if @empl_state.errors.any? %>
		<h2><%= pluralize(@empl_state.errors.count, "error") %> prevented this employment state from saving:</h2>

		<ul>
			<% @empl_state.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="panel-body">
		<p>
			<%= f.label :state_name %> <br>
			<%= f.text_field :state_name, class: 'form-control' %>
		</p>
		<p>
			<%= f.submit "Submit", class: "btn btn-primary" %>
		</p>
	</div>
<% end %>

eduly-jobs/app/views/empl_states/edit.html.erb
<h2 class="sub-header">Edit Employment State | <%= link_to "Back", empl_states_path %></h2>

<%= render 'form' %>

eduly-jobs/app/views/empl_states/index.html.erb
<h2 class="sub-header">List of Employment States | <%= link_to 'New Employment State', new_empl_state_path %></h2>

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>States</th>
				<th>Number of Cities</th>
				<th>Operations</th>
			</tr>
		</thead>
		<tbody>
			<% @empl_states.each do |empl_state| %>
			<tr>
				<td><%= empl_state.id %></td>
				<td><%= link_to empl_state.state_name, empl_state_path(empl_state) %></td>
				<td><%= empl_state.empl_cities.count %></td>
				<td>
					<%= link_to "Edit", edit_empl_state_path(empl_state) %> |
					<%= link_to "Delete", empl_state_path(empl_state), method: :delete, data: { confirm: 'Are you sure?' } %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>


<h2>Import Empl State</h2>

<%= form_tag import_empl_states_path, multipart: true do %>
	<%= file_field_tag :file %>
	<%= submit_tag "Import" %>
<% end %>

eduly-jobs/app/views/empl_states/new.html.erb
<h2 class="sub-header">New Employment State | <%= link_to "Back", empl_states_path %></h2>

<%= render 'form' %>

eduly-jobs/app/views/empl_states/show.html.erb
<h3><%= @empl_state.state_name %></h3>

<%= link_to 'Edit', edit_empl_state_path(@empl_state), class: "btn btn-md btn-danger", style: "color: white", role: "button" %> |
<%= link_to 'Delete', empl_state_path(@empl_state), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-md btn-danger", style: "color: white", role: "button" %> |
<%= link_to "Back", empl_states_path, class: "btn btn-md btn-danger", style: "color: white", role: "button" %>