Eduly Video Platform/eduly-cms-ms/config/routes.rb
Rails.application.routes.draw do
	root 'categories#index'

	resources :categories
	resources :topics
	resources :courses
end

Eduly Video Platform/eduly-cms-ms/app/models/category.rb
class Category < ActiveRecord::Base
	# Associations
	has_many :topics
	# Validations
	validates :category_title, :category_description, presence: true
end

Eduly Video Platform/eduly-cms-ms/app/models/course.rb
class Course < ActiveRecord::Base
	# Associations
	belongs_to :topic
	
	# Validations
	validates :topic_id, :course_title, :course_description, presence: true
end

Eduly Video Platform/eduly-cms-ms/app/models/topic.rb
class Topic < ActiveRecord::Base
	# Associations
	belongs_to :category
	has_many :courses

	# Validations
	validates :category_id, :topic_title, :topic_description, presence: true
end

Eduly Video Platform/eduly-cms-ms/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Eduly Video Platform/eduly-cms-ms/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :set_category, only: [:show, :edit, :update, :destroy]

	def index
		@categories = Category.all
	end

	def show
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to @category, notice: 'New category has been created successfully.'
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @category.update(category_params)
			redirect_to @category, notice: 'Category has been updated successfully.'
		else
			render 'edit'
		end
	end

	def destroy
		@category.destroy
		redirect_to categories_path, notice: 'Category has been deleted successfully.'
	end


	private
		def category_params
			params.require(:category).permit(:category_title, :category_description)
		end

		def set_category
			@category = Category.find(params[:id])
		end
end

Eduly Video Platform/eduly-cms-ms/app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	before_action :set_course, only: [:show, :edit, :update, :destroy]

	def index
		if params[:topic_id].present?
			@courses = Course.where(topic_id: params[:topic_id])
		else
			@courses = Course.all
		end
	end

	def show
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)

		if @course.save
			redirect_to @course, notice: 'New Course has been created successfully.'
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @course.update(course_params)
			redirect_to @course, notice: 'Course has been updated successfully.'
		else
			render 'new'
		end
	end

	def destroy
		@course.destroy
		redirect_to courses_path, notice: 'Course has been deleted successfully.'
	end


	private
		def course_params
			params.require(:course).permit(:topic_id, :course_title, :course_description)
		end

		def set_course
			@course = Course.find(params[:id])
		end
end

Eduly Video Platform/eduly-cms-ms/app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_action :set_topic, only: [:show, :edit, :update, :destroy]

	def index
		if params[:category_id].present?
			@topics = Topic.where(category_id: params[:category_id])
		else
			@topics = Topic.all
		end
	end

	def show
	end

	def new
		@topic = Topic.new
	end

	def create
		@topic = Topic.new(topic_params)

		if @topic.save
			redirect_to @topic, notice: 'New Topic has been created successfully.'
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @topic.update(topic_params)
			redirect_to @topic, notice: 'Topic has been updated successfully.'
		else
			render 'edit'
		end
	end

	def destroy
		@topic.destroy
		redirect_to topics_path, notice: 'Topic has been deleted successfully.'
	end


	private
		def topic_params
			params.require(:topic).permit(:category_id, :topic_title, :topic_description)
		end

		def set_topic
			@topic = Topic.find(params[:id])
		end
end

Eduly Video Platform/eduly-cms-ms/app/helpers/application_helper.rb
module ApplicationHelper
end

Eduly Video Platform/eduly-cms-ms/app/helpers/categories_helper.rb
module CategoriesHelper
end

Eduly Video Platform/eduly-cms-ms/app/helpers/courses_helper.rb
module CoursesHelper
end

Eduly Video Platform/eduly-cms-ms/app/helpers/topics_helper.rb
module TopicsHelper
end

Eduly Video Platform/eduly-cms-ms/app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
	<% if @category.errors.any? %>
		<h2><%= pluralize(@category.errors.count, "error") %> prevented this category from saving:</h2>

		<ul>
			<% @category.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="panel-body">
		<p>
			<%= f.label :category_title %> <br>
			<%= f.text_field :category_title, class: 'form-control' %>
		</p>
		<p>
			<%= f.label :category_description %> <br>
			<%= f.text_area :category_description, class: 'form-control' %>
		</p>
		<p>
			<%= f.submit "Submit", class: "btn btn-primary" %>
		</p>
	</div>
<% end %>

<br>
<%= link_to "Back", categories_path %>

Eduly Video Platform/eduly-cms-ms/app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

Eduly Video Platform/eduly-cms-ms/app/views/categories/index.html.erb
<%= link_to 'New Category', new_category_path %>

<ul>
	<% @categories.each do |category| %>
		<li>
			<%= link_to category.category_title, category_path(category) %> |
			<%= link_to 'Topics', topics_path(category_id: category.id) %>
		</li>
	<% end %>
</ul>

Eduly Video Platform/eduly-cms-ms/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

Eduly Video Platform/eduly-cms-ms/app/views/categories/show.html.erb
<h3><%= @category.category_title %></h3>

<p>
	<%= @category.category_description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> | 
<%= link_to 'Back', categories_path %>

Eduly Video Platform/eduly-cms-ms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EdulyCmsMs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>