eduly-jobs/config/routes.rb
Rails.application.routes.draw do

	root 'sessions#new'

	resources :landings, only: [:index]
	resources :empl_designations do
		post 'import', on: :collection
	end

	resources :empl_organisations do
		post 'import', on: :collection
	end

	resources :empl_cities do
		post 'import', on: :collection
	end

	resources :empl_job_types do
		post 'import', on: :collection
	end

	resources :empl_jobs do
		post 'import', on: :collection
	end

	resources :empl_states do
		post 'import', on: :collection
	end
	# Signup routes
	resources :admin_users, only: [:create]
	get "signup", to: "admin_users#new", as: "signup"

	# login routes
	resources :sessions, only: [:create]
	get "login", to: "sessions#new", as: "login"
	delete "logout", to: "sessions#destroy", as: "logout"

end

eduly-jobs/app/views/layouts/admin_welcome.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Login Eduly Jobs</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<meta charset="utf-8">
	<meta content="IE=edge" http-equiv="X-UA-Compatible">
	<meta content="width=device-width,initial-scale=1" name="viewport">
</head>

<body class="admin_welcome">

	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

		<%= yield %>
	</div>

</body>
</html>

eduly-jobs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>EdulyJobs</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<%= render 'layouts/shared/header' %>

	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-3 col-md-2 sidebar">
				<%= render 'layouts/shared/nav_sidebar' %>
			</div>

			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-info") %>
				<% end %>
				
				<%= yield %>
			</div>
		</div>
	</div>

	<%= render 'layouts/shared/footer' %>
</body>
</html>

eduly-jobs/app/views/layouts/index.html.erb
<h2 class="sub-header">List of Cities | <%= link_to "New City", new_city_path %></h2>

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>City</th>
				<th>State</th>
				<th>News Count</th>
				<th>Last News Release</th>
				<th>Operations</th>
			</tr>
		</thead>
		<tbody>
			<% @cities.each do |city| %>
			<tr>
				<td><%= city.id %></td>
				<td><%= city.city_name %></td>
				<td><%= city.state.state_name %></td>
				<td><%= city.news_articles.count %></td>
				<td><%= city.news_articles.last.created_at.strftime("%B %d, %Y") %></td>
				<td>
					<%= link_to "Edit", edit_city_path(city) %> |
					<%= link_to "Delete", city_path(city), method: :delete, data: { confirm: 'Are you sure?' } %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>